@HostAddress = http://localhost:5122

GET {{HostAddress}}/products
Content-Type: none

###

GET {{HostAddress}}/products/0196960d-9e4e-7585-9c74-86f60257d0e0
Content-Type: none

###

POST {{HostAddress}}/products
Content-Type: application/json

{
  "Name": "SK Hynix Internal SSD",
  "Description": "SK Hynix Gold P31 1TB PCIe NVMe Gen3 M.2 2280 Internal SSD read up to 3500MB/s and write up to 3200MB/s.",
  "Quantity": 1,
  "Price": 119.99
}

###

PUT {{HostAddress}}/products/
Content-Type: application/json

{
  "id": "0196960d-4839-7971-8eb7-a37633230f2b",
  "name": "Gaming Mice",
  "description": "A high-performance low-latency light-wight mice for gaming.",
  "quantity": 22,
  "price": 68.99
}

###

DELETE {{HostAddress}}/products/5c492ba0-3d44-402a-966e-56b578cf0648
Content-Type: none

###